apiVersion: v1
kind: PersistentVolume
metadata:
  name: redis-pv
spec:
  accessModes:
  - ReadWriteOnce
  capacity:
    storage: 200Mi
  local:
    path: /kubernetes/volumes/redis
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - firewire-orion
  persistentVolumeReclaimPolicy: Delete
  storageClassName: local-storage
  volumeMode: Filesystem

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: redis-pvc

  labels:
  namespace: default
spec:
  accessModes:
    - ReadWriteOnce
#    - string
  resources:
    requests:
      storage: 200Mi
  storageClassName: local-storage
  volumeMode: Filesystem
  volumeName: redis-pv

